{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap-iam.credentialsSecretName" . }}
  labels:
    {{- include "openldap-iam.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.credentials.adminPassword | quote }}
  config-password: {{ .Values.credentials.configPassword | quote }}
  lam-config-password: {{ .Values.credentials.lamConfigPassword | quote }}
{{- end }}
